//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsc_harambe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class harambeDBEntities : DbContext
    {
        public harambeDBEntities()
            : base("name=harambeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestValue> TestValues { get; set; }
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<hotels> hotels { get; set; }
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<plans> plans { get; set; }
        public virtual DbSet<transport> transport { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<statistics_activities> statistics_activities { get; set; }
        public virtual DbSet<statistics_food> statistics_food { get; set; }
        public virtual DbSet<statistics_images> statistics_images { get; set; }
        public virtual DbSet<statistics_transport> statistics_transport { get; set; }
    }
}
