//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsc_harambe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistics_food
    {
        public int id { get; set; }
        public Nullable<int> users_id { get; set; }
        public Nullable<int> hotel_id { get; set; }
        public string naziv { get; set; }
        public Nullable<int> cnt { get; set; }
        public string hotel_name { get; set; }
    }
}
